# Generated by Django 5.0.1 on 2024-02-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
