# Generated by Django 5.0.1 on 2024-02-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Archive', 'Archive'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255),
        ),
    ]
