# Generated by Django 5.0.2 on 2024-02-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timesheet.employee'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
