# Generated by Django 5.0.2 on 2024-02-13 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_project_lead_id_alter_client_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('hours', models.IntegerField()),
                ('overtime', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.category')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.client')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
