# Generated by Django 5.0.2 on 2024-02-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='employee_id',
        ),
    ]
