# Generated by Django 5.0.2 on 2024-02-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_employee_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
