# Generated by Django 5.0.2 on 2024-02-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0015_rename_category_id_task_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='employee',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_id',
        ),
    ]
