# Generated by Django 5.0.2 on 2024-02-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0017_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
